### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by brokenseal** [TIBCOSoftware/JS-FDSample#2]
Hello,
on point number 2 of the installation process, you point to a non-existing file (FRESHDELIVERY_PATH/JasperServerResources/freshDelivery-RepositoryExport.zip), I'm assuming you're referring to FRESHDELIVERY_PATH/JasperServerResources/FreshDelivery-Repository-Large.zip

Cheers,
Davide

**Comment by ernestoongaro** [comment]
Thanks @brokenseal, need to clean up that folder - will do it in one go

**Comment by dmitrygorbenko** [comment]
Bumping up this issue !
I guess the file should be: FreshDelivery-Standard-6_1.zip
